// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prototest.proto

package com.example.demo.grpc;

public final class Prototest {
  private Prototest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_TextMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_TextMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_TextRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_TextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_TextResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_TextResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017prototest.proto\022\025com.example.demo.grpc" +
      "\"\033\n\013TextMessage\022\014\n\004text\030\001 \001(\t\"E\n\013TextReq" +
      "uest\0226\n\nreqTextMsg\030\001 \001(\0132\".com.example.d" +
      "emo.grpc.TextMessage\"F\n\014TextResponse\0226\n\n" +
      "resTextMsg\030\001 \001(\0132\".com.example.demo.grpc" +
      ".TextMessage2e\n\013TextService\022V\n\tprotoTest" +
      "\022\".com.example.demo.grpc.TextRequest\032#.c" +
      "om.example.demo.grpc.TextResponse\"\000B\002P\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_demo_grpc_TextMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_grpc_TextMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_TextMessage_descriptor,
        new String[] { "Text", });
    internal_static_com_example_demo_grpc_TextRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_demo_grpc_TextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_TextRequest_descriptor,
        new String[] { "ReqTextMsg", });
    internal_static_com_example_demo_grpc_TextResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_demo_grpc_TextResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_TextResponse_descriptor,
        new String[] { "ResTextMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
