// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.example.demo.grpc;

public final class Search {
  private Search() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_UserMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_UserMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_grpc_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_grpc_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014search.proto\022\025com.example.demo.grpc\"I\n" +
      "\013UserMessage\022\n\n\002id\030\001 \001(\005\022\017\n\007user_id\030\002 \001(" +
      "\t\022\n\n\002pw\030\003 \001(\t\022\021\n\timage_url\030\004 \001(\t\"E\n\013User" +
      "Request\0226\n\nreqTextMsg\030\001 \001(\0132\".com.exampl" +
      "e.demo.grpc.UserMessage\"F\n\014UserResponse\022" +
      "6\n\nresTextMsg\030\001 \001(\0132\".com.example.demo.g" +
      "rpc.UserMessage2d\n\013UserService\022U\n\010UserTe" +
      "st\022\".com.example.demo.grpc.UserRequest\032#" +
      ".com.example.demo.grpc.UserResponse\"\000B\002P" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_demo_grpc_UserMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_grpc_UserMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_UserMessage_descriptor,
        new String[] { "Id", "UserId", "Pw", "ImageUrl", });
    internal_static_com_example_demo_grpc_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_demo_grpc_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_UserRequest_descriptor,
        new String[] { "ReqTextMsg", });
    internal_static_com_example_demo_grpc_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_demo_grpc_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_grpc_UserResponse_descriptor,
        new String[] { "ResTextMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
