// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prototest.proto

package com.example.demo.grpc;

/**
 * Protobuf type {@code com.example.demo.grpc.TextRequest}
 */
public  final class TextRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.demo.grpc.TextRequest)
    TextRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TextRequest.newBuilder() to construct.
  private TextRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TextRequest() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TextRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            TextMessage.Builder subBuilder = null;
            if (reqTextMsg_ != null) {
              subBuilder = reqTextMsg_.toBuilder();
            }
            reqTextMsg_ = input.readMessage(TextMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reqTextMsg_);
              reqTextMsg_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Prototest.internal_static_com_example_demo_grpc_TextRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Prototest.internal_static_com_example_demo_grpc_TextRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TextRequest.class, Builder.class);
  }

  public static final int REQTEXTMSG_FIELD_NUMBER = 1;
  private TextMessage reqTextMsg_;
  /**
   * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
   */
  public boolean hasReqTextMsg() {
    return reqTextMsg_ != null;
  }
  /**
   * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
   */
  public TextMessage getReqTextMsg() {
    return reqTextMsg_ == null ? TextMessage.getDefaultInstance() : reqTextMsg_;
  }
  /**
   * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
   */
  public com.example.demo.grpc.TextMessageOrBuilder getReqTextMsgOrBuilder() {
    return getReqTextMsg();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reqTextMsg_ != null) {
      output.writeMessage(1, getReqTextMsg());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reqTextMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getReqTextMsg());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TextRequest)) {
      return super.equals(obj);
    }
    TextRequest other = (TextRequest) obj;

    boolean result = true;
    result = result && (hasReqTextMsg() == other.hasReqTextMsg());
    if (hasReqTextMsg()) {
      result = result && getReqTextMsg()
          .equals(other.getReqTextMsg());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReqTextMsg()) {
      hash = (37 * hash) + REQTEXTMSG_FIELD_NUMBER;
      hash = (53 * hash) + getReqTextMsg().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TextRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TextRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TextRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TextRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TextRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TextRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TextRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TextRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TextRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TextRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TextRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TextRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TextRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.grpc.TextRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.grpc.TextRequest)
      com.example.demo.grpc.TextRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Prototest.internal_static_com_example_demo_grpc_TextRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Prototest.internal_static_com_example_demo_grpc_TextRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TextRequest.class, Builder.class);
    }

    // Construct using com.example.demo.grpc.TextRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (reqTextMsgBuilder_ == null) {
        reqTextMsg_ = null;
      } else {
        reqTextMsg_ = null;
        reqTextMsgBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Prototest.internal_static_com_example_demo_grpc_TextRequest_descriptor;
    }

    public TextRequest getDefaultInstanceForType() {
      return TextRequest.getDefaultInstance();
    }

    public TextRequest build() {
      TextRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public TextRequest buildPartial() {
      TextRequest result = new TextRequest(this);
      if (reqTextMsgBuilder_ == null) {
        result.reqTextMsg_ = reqTextMsg_;
      } else {
        result.reqTextMsg_ = reqTextMsgBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TextRequest) {
        return mergeFrom((TextRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TextRequest other) {
      if (other == TextRequest.getDefaultInstance()) return this;
      if (other.hasReqTextMsg()) {
        mergeReqTextMsg(other.getReqTextMsg());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TextRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TextRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private TextMessage reqTextMsg_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        TextMessage, TextMessage.Builder, com.example.demo.grpc.TextMessageOrBuilder> reqTextMsgBuilder_;
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    public boolean hasReqTextMsg() {
      return reqTextMsgBuilder_ != null || reqTextMsg_ != null;
    }
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    public TextMessage getReqTextMsg() {
      if (reqTextMsgBuilder_ == null) {
        return reqTextMsg_ == null ? TextMessage.getDefaultInstance() : reqTextMsg_;
      } else {
        return reqTextMsgBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    public Builder setReqTextMsg(TextMessage value) {
      if (reqTextMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reqTextMsg_ = value;
        onChanged();
      } else {
        reqTextMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    public Builder setReqTextMsg(
        TextMessage.Builder builderForValue) {
      if (reqTextMsgBuilder_ == null) {
        reqTextMsg_ = builderForValue.build();
        onChanged();
      } else {
        reqTextMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    public Builder mergeReqTextMsg(TextMessage value) {
      if (reqTextMsgBuilder_ == null) {
        if (reqTextMsg_ != null) {
          reqTextMsg_ =
            TextMessage.newBuilder(reqTextMsg_).mergeFrom(value).buildPartial();
        } else {
          reqTextMsg_ = value;
        }
        onChanged();
      } else {
        reqTextMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    public Builder clearReqTextMsg() {
      if (reqTextMsgBuilder_ == null) {
        reqTextMsg_ = null;
        onChanged();
      } else {
        reqTextMsg_ = null;
        reqTextMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    public TextMessage.Builder getReqTextMsgBuilder() {
      
      onChanged();
      return getReqTextMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    public com.example.demo.grpc.TextMessageOrBuilder getReqTextMsgOrBuilder() {
      if (reqTextMsgBuilder_ != null) {
        return reqTextMsgBuilder_.getMessageOrBuilder();
      } else {
        return reqTextMsg_ == null ?
            TextMessage.getDefaultInstance() : reqTextMsg_;
      }
    }
    /**
     * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        TextMessage, TextMessage.Builder, com.example.demo.grpc.TextMessageOrBuilder>
        getReqTextMsgFieldBuilder() {
      if (reqTextMsgBuilder_ == null) {
        reqTextMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            TextMessage, TextMessage.Builder, com.example.demo.grpc.TextMessageOrBuilder>(
                getReqTextMsg(),
                getParentForChildren(),
                isClean());
        reqTextMsg_ = null;
      }
      return reqTextMsgBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.demo.grpc.TextRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.grpc.TextRequest)
  private static final TextRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TextRequest();
  }

  public static TextRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TextRequest>
      PARSER = new com.google.protobuf.AbstractParser<TextRequest>() {
    public TextRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TextRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TextRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TextRequest> getParserForType() {
    return PARSER;
  }

  public TextRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

