// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prototest.proto

package com.example.demo.grpc;

public interface TextRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.TextRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
   */
  boolean hasReqTextMsg();
  /**
   * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
   */
  TextMessage getReqTextMsg();
  /**
   * <code>.com.example.demo.grpc.TextMessage reqTextMsg = 1;</code>
   */
  TextMessageOrBuilder getReqTextMsgOrBuilder();
}
