// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.example.demo.grpc;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
   */
  boolean hasReqTextMsg();
  /**
   * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
   */
  com.example.demo.grpc.UserMessage getReqTextMsg();
  /**
   * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
   */
  com.example.demo.grpc.UserMessageOrBuilder getReqTextMsgOrBuilder();
}
