// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.example.demo.grpc;

public interface UserMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.UserMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string pw = 3;</code>
   */
  java.lang.String getPw();
  /**
   * <code>string pw = 3;</code>
   */
  com.google.protobuf.ByteString
      getPwBytes();

  /**
   * <code>string image_url = 4;</code>
   */
  java.lang.String getImageUrl();
  /**
   * <code>string image_url = 4;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();
}
