// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.example.demo.grpc;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.grpc.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.grpc.UserMessage resTextMsg = 1;</code>
   */
  boolean hasResTextMsg();
  /**
   * <code>.com.example.demo.grpc.UserMessage resTextMsg = 1;</code>
   */
  com.example.demo.grpc.UserMessage getResTextMsg();
  /**
   * <code>.com.example.demo.grpc.UserMessage resTextMsg = 1;</code>
   */
  com.example.demo.grpc.UserMessageOrBuilder getResTextMsgOrBuilder();
}
