// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.example.demo.grpc;

/**
 * Protobuf type {@code com.example.demo.grpc.UserRequest}
 */
public  final class UserRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.demo.grpc.UserRequest)
    UserRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserRequest.newBuilder() to construct.
  private UserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.example.demo.grpc.UserMessage.Builder subBuilder = null;
            if (reqTextMsg_ != null) {
              subBuilder = reqTextMsg_.toBuilder();
            }
            reqTextMsg_ = input.readMessage(com.example.demo.grpc.UserMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reqTextMsg_);
              reqTextMsg_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.grpc.Search.internal_static_com_example_demo_grpc_UserRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.grpc.Search.internal_static_com_example_demo_grpc_UserRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.grpc.UserRequest.class, com.example.demo.grpc.UserRequest.Builder.class);
  }

  public static final int REQTEXTMSG_FIELD_NUMBER = 1;
  private com.example.demo.grpc.UserMessage reqTextMsg_;
  /**
   * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
   */
  public boolean hasReqTextMsg() {
    return reqTextMsg_ != null;
  }
  /**
   * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
   */
  public com.example.demo.grpc.UserMessage getReqTextMsg() {
    return reqTextMsg_ == null ? com.example.demo.grpc.UserMessage.getDefaultInstance() : reqTextMsg_;
  }
  /**
   * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
   */
  public com.example.demo.grpc.UserMessageOrBuilder getReqTextMsgOrBuilder() {
    return getReqTextMsg();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reqTextMsg_ != null) {
      output.writeMessage(1, getReqTextMsg());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reqTextMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getReqTextMsg());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.grpc.UserRequest)) {
      return super.equals(obj);
    }
    com.example.demo.grpc.UserRequest other = (com.example.demo.grpc.UserRequest) obj;

    boolean result = true;
    result = result && (hasReqTextMsg() == other.hasReqTextMsg());
    if (hasReqTextMsg()) {
      result = result && getReqTextMsg()
          .equals(other.getReqTextMsg());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReqTextMsg()) {
      hash = (37 * hash) + REQTEXTMSG_FIELD_NUMBER;
      hash = (53 * hash) + getReqTextMsg().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.grpc.UserRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.grpc.UserRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.demo.grpc.UserRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.grpc.UserRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.grpc.UserRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.grpc.UserRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.grpc.UserRequest)
      com.example.demo.grpc.UserRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.grpc.Search.internal_static_com_example_demo_grpc_UserRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.grpc.Search.internal_static_com_example_demo_grpc_UserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.grpc.UserRequest.class, com.example.demo.grpc.UserRequest.Builder.class);
    }

    // Construct using com.example.demo.grpc.UserRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (reqTextMsgBuilder_ == null) {
        reqTextMsg_ = null;
      } else {
        reqTextMsg_ = null;
        reqTextMsgBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.grpc.Search.internal_static_com_example_demo_grpc_UserRequest_descriptor;
    }

    public com.example.demo.grpc.UserRequest getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    public com.example.demo.grpc.UserRequest build() {
      com.example.demo.grpc.UserRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.demo.grpc.UserRequest buildPartial() {
      com.example.demo.grpc.UserRequest result = new com.example.demo.grpc.UserRequest(this);
      if (reqTextMsgBuilder_ == null) {
        result.reqTextMsg_ = reqTextMsg_;
      } else {
        result.reqTextMsg_ = reqTextMsgBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.grpc.UserRequest) {
        return mergeFrom((com.example.demo.grpc.UserRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.grpc.UserRequest other) {
      if (other == getDefaultInstance()) return this;
      if (other.hasReqTextMsg()) {
        mergeReqTextMsg(other.getReqTextMsg());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.demo.grpc.UserRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.demo.grpc.UserRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.example.demo.grpc.UserMessage reqTextMsg_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.grpc.UserMessage, com.example.demo.grpc.UserMessage.Builder, com.example.demo.grpc.UserMessageOrBuilder> reqTextMsgBuilder_;
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    public boolean hasReqTextMsg() {
      return reqTextMsgBuilder_ != null || reqTextMsg_ != null;
    }
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    public com.example.demo.grpc.UserMessage getReqTextMsg() {
      if (reqTextMsgBuilder_ == null) {
        return reqTextMsg_ == null ? com.example.demo.grpc.UserMessage.getDefaultInstance() : reqTextMsg_;
      } else {
        return reqTextMsgBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    public Builder setReqTextMsg(com.example.demo.grpc.UserMessage value) {
      if (reqTextMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reqTextMsg_ = value;
        onChanged();
      } else {
        reqTextMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    public Builder setReqTextMsg(
        com.example.demo.grpc.UserMessage.Builder builderForValue) {
      if (reqTextMsgBuilder_ == null) {
        reqTextMsg_ = builderForValue.build();
        onChanged();
      } else {
        reqTextMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    public Builder mergeReqTextMsg(com.example.demo.grpc.UserMessage value) {
      if (reqTextMsgBuilder_ == null) {
        if (reqTextMsg_ != null) {
          reqTextMsg_ =
            com.example.demo.grpc.UserMessage.newBuilder(reqTextMsg_).mergeFrom(value).buildPartial();
        } else {
          reqTextMsg_ = value;
        }
        onChanged();
      } else {
        reqTextMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    public Builder clearReqTextMsg() {
      if (reqTextMsgBuilder_ == null) {
        reqTextMsg_ = null;
        onChanged();
      } else {
        reqTextMsg_ = null;
        reqTextMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    public com.example.demo.grpc.UserMessage.Builder getReqTextMsgBuilder() {
      
      onChanged();
      return getReqTextMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    public com.example.demo.grpc.UserMessageOrBuilder getReqTextMsgOrBuilder() {
      if (reqTextMsgBuilder_ != null) {
        return reqTextMsgBuilder_.getMessageOrBuilder();
      } else {
        return reqTextMsg_ == null ?
            com.example.demo.grpc.UserMessage.getDefaultInstance() : reqTextMsg_;
      }
    }
    /**
     * <code>.com.example.demo.grpc.UserMessage reqTextMsg = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.demo.grpc.UserMessage, com.example.demo.grpc.UserMessage.Builder, com.example.demo.grpc.UserMessageOrBuilder> 
        getReqTextMsgFieldBuilder() {
      if (reqTextMsgBuilder_ == null) {
        reqTextMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.demo.grpc.UserMessage, com.example.demo.grpc.UserMessage.Builder, com.example.demo.grpc.UserMessageOrBuilder>(
                getReqTextMsg(),
                getParentForChildren(),
                isClean());
        reqTextMsg_ = null;
      }
      return reqTextMsgBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.demo.grpc.UserRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.grpc.UserRequest)
  private static final com.example.demo.grpc.UserRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.grpc.UserRequest();
  }

  public static com.example.demo.grpc.UserRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserRequest>
      PARSER = new com.google.protobuf.AbstractParser<UserRequest>() {
    public UserRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserRequest> getParserForType() {
    return PARSER;
  }

  public com.example.demo.grpc.UserRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

